[package]
name = "rust-riscv32i"
version = "0.1.0"
edition = "2024"

[dependencies]

[build]
target = "riscv32i-unknown-none-elf"

[target.riscv32i-unknown-none-elf]
rustflags = ["-C", "split-debuginfo=off"]

